### ISSUE TITLE
NoneType not subscriptable

### ISSUE THREAD

**Issue by proycon** [knaw-huc/pagexml#1]
I ran into an issue parsing the GA ground truth corpus (haven't pinpointed yet exactly on what input it fails), but some extra checks may be needed to prevent this:

```
Traceback (most recent call last):
  File "/home/proycon/work/golden-agents-htr/scripts/extract-text.py", line 13, in <module>
    scan = parse_pagexml_file(filename)
  File "/home/proycon/work/golden-agents-htr/env/lib/python3.10/site-packages/pagexml/parser.py", line 199, in parse_pagexml_file
    scan_doc = parse_pagexml_json(scan_json)
  File "/home/proycon/work/golden-agents-htr/env/lib/python3.10/site-packages/pagexml/parser.py", line 217, in parse_pagexml_json
    text_regions = parse_textregion_list(scan_json['TextRegion'])
  File "/home/proycon/work/golden-agents-htr/env/lib/python3.10/site-packages/pagexml/parser.py", line 136, in parse_textregion_list
    return [parse_textregion(textregion_dict) for textregion_dict in textregion_dict_list]
  File "/home/proycon/work/golden-agents-htr/env/lib/python3.10/site-packages/pagexml/parser.py", line 136, in <listcomp>
    return [parse_textregion(textregion_dict) for textregion_dict in textregion_dict_list]
  File "/home/proycon/work/golden-agents-htr/env/lib/python3.10/site-packages/pagexml/parser.py", line 122, in parse_textregion
    text_region.lines = [parse_textline(text_region_dict['TextLine'])]
  File "/home/proycon/work/golden-agents-htr/env/lib/python3.10/site-packages/pagexml/parser.py", line 71, in parse_textline
    words=parse_line_words(textline),
  File "/home/proycon/work/golden-agents-htr/env/lib/python3.10/site-packages/pagexml/parser.py", line 35, in parse_line_words
    unicode_string = word_dict["TextEquiv"]["Unicode"]['#text']
TypeError: 'NoneType' object is not subscriptable
```

**Comment by proycon** [comment]
I can't reproduce this anymore after upgrading (may have been on an older version), so probably already solved. Closing

**Comment by brambg** [comment]
I remember running into this problem, too.
https://github.com/knaw-huc/pagexml/commit/4c9962848093a5d2af1d1ddead5b46973229396b fixed it for me.
